common:
        loglevel: debug

prod:
        loglevel: warn
        storage: local
        storage_path: /docker-registry-storage

local:
        loglevel: warn
        storage: local
        storage_path: /docker-registry-storage
